// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import errors "github.com/pkg/errors"
import mock "github.com/stretchr/testify/mock"

// StackTracer is an autogenerated mock type for the StackTracer type
type StackTracer struct {
	mock.Mock
}

// StackTrace provides a mock function with given fields:
func (_m *StackTracer) StackTrace() errors.StackTrace {
	ret := _m.Called()

	var r0 errors.StackTrace
	if rf, ok := ret.Get(0).(func() errors.StackTrace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.StackTrace)
		}
	}

	return r0
}
