// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import "github.com/appoptics/appoptics-apm-go/v1/ao/internal/reporter/collector"

// FIX: gRPC generated file use x/net/context - import context "context"
import "golang.org/x/net/context"
import "google.golang.org/grpc"
import "github.com/stretchr/testify/mock"

// TraceCollectorClient is an autogenerated mock type for the TraceCollectorClient type
type TraceCollectorClient struct {
	mock.Mock
}

// GetSettings provides a mock function with given fields: ctx, in, opts
func (_m *TraceCollectorClient) GetSettings(ctx context.Context, in *collector.SettingsRequest, opts ...grpc.CallOption) (*collector.SettingsResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *collector.SettingsResult
	if rf, ok := ret.Get(0).(func(context.Context, *collector.SettingsRequest, ...grpc.CallOption) *collector.SettingsResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.SettingsResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *collector.SettingsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *TraceCollectorClient) Ping(ctx context.Context, in *collector.PingRequest, opts ...grpc.CallOption) (*collector.MessageResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *collector.MessageResult
	if rf, ok := ret.Get(0).(func(context.Context, *collector.PingRequest, ...grpc.CallOption) *collector.MessageResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.MessageResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *collector.PingRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostEvents provides a mock function with given fields: ctx, in, opts
func (_m *TraceCollectorClient) PostEvents(ctx context.Context, in *collector.MessageRequest, opts ...grpc.CallOption) (*collector.MessageResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *collector.MessageResult
	if rf, ok := ret.Get(0).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) *collector.MessageResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.MessageResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostMetrics provides a mock function with given fields: ctx, in, opts
func (_m *TraceCollectorClient) PostMetrics(ctx context.Context, in *collector.MessageRequest, opts ...grpc.CallOption) (*collector.MessageResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *collector.MessageResult
	if rf, ok := ret.Get(0).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) *collector.MessageResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.MessageResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostStatus provides a mock function with given fields: ctx, in, opts
func (_m *TraceCollectorClient) PostStatus(ctx context.Context, in *collector.MessageRequest, opts ...grpc.CallOption) (*collector.MessageResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *collector.MessageResult
	if rf, ok := ret.Get(0).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) *collector.MessageResult); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collector.MessageResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *collector.MessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
